variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "private_app_subnet_az1_cidr" {}
variable "private_app_subnet_az2_cidr" {}
variable "private_data_subnet_az1_cidr" {}
variable "private_data_subnet_az2_cidr" {}
variable "public_subnet_az1_abs" {}
variable "public_subnet_az2_abs" {}
variable "private_app_subnet_az1_abs" {}
variable "private_app_subnet_az2_abs" {}
variable "private_data_subnet_az1_abs" {}
variable "private_data_subnet_az2_abs" {}

variable "project_name2" {}
variable "vpc_cidr1" {}
variable "public_subnet_az1_cidr_dev" {}
variable "public_subnet_az2_cidr_dev" {}
variable "private_app_subnet_az1_cidr_dev" {}
variable "private_app_subnet_az2_cidr_dev" {}
variable "private_data_subnet_az1_cidr_dev" {}
variable "private_data_subnet_az2_cidr_dev" {}
variable "public_subnet_az1_dev" {}
variable "public_subnet_az2_dev" {}
variable "private_app_subnet_az1_dev" {}
variable "private_app_subnet_az2_dev" {}
variable "private_data_subnet_az1_dev" {}
variable "private_data_subnet_az2_dev" {}

